##############################################################
# This function takes a Bayes Factor analysis generated from #
# BEAST and SPREAD3, and develops a map to visualise highly  #
# supported routes of spread                                 #
##############################################################

bf_maps <- function(BFfile_dir, 
                    coordinate_dir,
                    locationGroup_dir,
                    col_list,
                    spdf,
                    graph_title) {
  
  BFs <- read.csv(BFfile_dir) #load bayes factor results
  coords <- read.table(coordinate_dir, 
                       header = FALSE) #load location coordinate table
  names(coords) <- c("location", "Lat", "Long") #rename the headers
  
  # join BFs and coords together by "FROM" column 
  BFs$location <- BFs$FROM # create a new "location" column in the BFs dataset to match with the coords dataset 
  coords_start <- coords # create a new coords table
  names(coords_start) <- c("location", "start_y", "start_x") # rename new table
  BFs <- (merge(coords_start, BFs, by = 'location')) # merge BFs and coords by "location"
  
  # repeat for the "TO" column
  
  BFs$location <- BFs$TO # create a new "location" column in the BFs dataset to match with the coords dataset 
  coords_end <- coords # create a new coords table
  names(coords_end) <- c("location", "end_y", "end_x") # rename new table
  BFs <- (merge(coords_end, BFs, by = 'location')) # merge BFs and coords by "location"
  
  # The tables generated by SPREAD3 just provide a Bayes Factor 
  # value. I wanted to only visualise the most highly supported 
  # routes, using a standard Bayes Factor classification which I
  # defined here.
  
  BFs$BF_classification <- cut(BFs$BAYES_FACTOR, 
                               breaks = c(-Inf, 3, 6, 10, 30, 100, Inf), # groups Bayes Factor results into different categories
                               labels = c("No support",
                                          "Marginally supported transition", 
                                          "Supported transition", 
                                          "Strongly supported transition", 
                                          "Very strongly supported transition", 
                                          "Definitive transition"), 
                               right = FALSE)
  
  BFs$BF_classification_no <- cut(BFs$BAYES_FACTOR, 
                                  breaks = c(-Inf, 3, 6, 10, 30, 100, Inf), 
                                  labels = c(0,1,2,3,4,5), # it's easier to work with numbers, so I recoded the classifications again
                                  right = FALSE)
  
  
  # I wanted to add some polylines which represent the Bayes
  # factor transmission routes. Polylines will likely overlap
  # hence I wanted to develop a colouring system whereby lines going
  # easterly were orange, and lines moving westerly were green.
  
  BFs$Direction <- ifelse(BFs$end_x < BFs$start_x, "West", "East") # add a new field to classify movement direction
  
  
  
  # I grouped admin regions to represent the Economic divisions
  # of China. This was done to make the map look more clean.
  
  ED <- read.csv(locationGroup_dir, #load ED grouping
                 header = FALSE) 
  names(ED) <- c("NAME_1", "NAME_1_new") # Rename grouping table 
  spdf <- merge(spdf, ED, by.x="NAME_1", by.y="NAME_1") #this adds a new field to the spatial dataframe 
  union <- unionSpatialPolygons(spdf, spdf@data$NAME_1_new) # Dissolve polygons into the new ED groupings 
  union.id <- getSpPPolygonsIDSlots(union) # find ID
  newdata <- data.frame(col_list, union.id) # create dataframe with colours
  row.names(newdata) <- union.id # define row names
  names(newdata) <- c("colours","id") # define column names
  new_spdf <- SpatialPolygonsDataFrame(union, data = newdata) #create another polygon with colours
  spdtab <- fortify(new_spdf) # fortify
  gislayerdata <- mutate(as.data.frame(new_spdf$id), id = as.character(row_number()))
  names(gislayerdata) <- c("id", "NUMBER_ID")
  spdtab <- inner_join(spdtab, gislayerdata, "id") # join spatial data frame to GIS layer using ID column
  
  # create map 
  
  p1 <-ggplot(new_spdf, aes(x = long, y = lat)) +
    
    geom_polygon(data=spdtab, #colour the polygons according to ED region
                 aes(group = group,
                     fill = id,
                     alpha=0.5)) +
    
    geom_path(data=spdf, #create a white border around each admin region
              colour = "white",
              aes(group = group,
                  alpha = 0.5
                  
              ), 
              size=0.05) +
    
    scale_fill_manual(values = col_list) + # add colours defined earlier
    
    # West = grey90
    # Very strongly supported transition = 4
    # white
    
    geom_curve(data=subset(BFs,BF_classification_no==4 & Direction =="West"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.30,
               position = position_dodge(width = 0.5),
               colour = "white",
               lwd=2,
               ncp= 200) +
    
    #colour
    geom_curve(data=subset(BFs,BF_classification_no==4 & Direction =="West"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.30,
               position = position_dodge(width = 0.5),
               lwd=1,
               ncp= 200,
               colour = "grey90") +
    
    
    # East = grey50
    # Very strongly supported transition = 4
    # white
    geom_curve(data=subset(BFs,BF_classification_no==4 & Direction =="East"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.30,
               position = position_dodge(width = 0.5),
               colour = "white",
               lwd=2,
               ncp= 200) +
    
    #colour
    geom_curve(data=subset(BFs,BF_classification_no==4 & Direction =="East"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.30,
               position = position_dodge(width = 0.5),
               lwd=1,
               ncp= 200,
               colour = "grey50") +
    
    # West = grey90
    # Strongly supported transition = 5
    # white
    geom_curve(data=subset(BFs,BF_classification_no==5 & Direction =="West"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.50,
               position = position_dodge(width = 0.5),
               colour = "white",
               lwd=3,
               ncp= 200) +
    
    #colour
    geom_curve(data=subset(BFs,BF_classification_no==5 & Direction =="West"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.50,
               position = position_dodge(width = 0.5),
               lwd=2,
               ncp= 200,
               colour = "grey90") +
    
    # East = grey50
    # Strongly supported transition = 5
    # white
    geom_curve(data=subset(BFs,BF_classification_no==5 & Direction =="East"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y), 
               curvature = 0.50,
               position = position_dodge(width = 0.5),
               colour = "white",
               lwd=3,
               ncp= 200) +
    
    #colour
    geom_curve(data=subset(BFs,BF_classification_no==5 & Direction =="East"), 
               aes(x = start_x, 
                   y = start_y,
                   xend = end_x, 
                   yend = end_y),  
               curvature = 0.50,
               position = position_dodge(width = 0.5),
               lwd=2,
               ncp= 200,
               colour = "grey50") +
    
    #other stuff
    theme(plot.title = element_text(margin = margin(b = -10)), 
          axis.line=element_blank(),
          axis.text.x=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks=element_blank(),
          axis.title.x=element_blank(),
          axis.title.y=element_blank(),panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.background = element_blank(),
          legend.position = "none") +
    
    # add black points to represent coordinates
    geom_point(data = coords, 
               aes(x = Long, 
                   y = Lat), 
               shape = 21, 
               colour = "white", 
               fill = "black", 
               size = 2, stroke = 1) +
    
    # add labels 
    geom_text_repel(data=coords, 
                    aes(x = Long, y = Lat, label = location), 
                    size=3) +
    ggtitle(graph_title)
  
  assign(graph_title, p1, .GlobalEnv) #assigns graph to global environment
  print(p1)
  
}
